stages:
- deploy

variables:
  DOCKER_HOST: "dock-one.mars.haw-hamburg.de:5555"
  DOCKER_REGISTRY: "artifactory.mars.haw-hamburg.de:5002"
  SERVIE_NAME: "geoserver"

deploy:
  stage: deploy
  script:
    - docker build -t $SERVIE_NAME:latest .
    - docker tag $SERVIE_NAME:latest $DOCKER_REGISTRY/$SERVIE_NAME:$CI_BUILD_ID
    - docker tag $SERVIE_NAME:latest $DOCKER_REGISTRY/$SERVIE_NAME:latest
    - docker tag $SERVIE_NAME:latest $DOCKER_REGISTRY/$SERVIE_NAME:$CI_BUILD_REF
    - docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_PW $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME:$CI_BUILD_ID
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME:latest
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME:$CI_BUILD_REF
