stages:
- deploy

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_REGISTRY: "nexus.informatik.haw-hamburg.de"
  SERVIE_NAME: "geoserver"

deploy:
  stage: deploy
  services:
    - $DOCKER_REGISTRY/docker:stable-dind
  only:
    - master
  script:
    - docker login -u $NEXUS_USER -p $NEXUS_PW $DOCKER_REGISTRY
    - docker build -t $SERVIE_NAME:latest .
    - docker tag $SERVIE_NAME:latest $DOCKER_REGISTRY/$SERVIE_NAME:$CI_PIPELINE_ID
    - docker tag $SERVIE_NAME:latest $DOCKER_REGISTRY/$SERVIE_NAME:latest
    - docker tag $SERVIE_NAME:latest $DOCKER_REGISTRY/$SERVIE_NAME:$CI_COMMIT_SHA
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME:$CI_PIPELINE_ID
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME:latest
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME:$CI_COMMIT_SHA
  tags:
    - k8s
